apiVersion: v1
kind: Service
metadata:
  name: myapp-service-loadbalancer
spec:
  selector:
    app: myapp
  ports:
    - name: http
      port: 5000           # Port exposed inside the cluster
  targetPort: 5000     # Port on the container
  type: LoadBalancer
